FROM alpine
MAINTAINER Tdtool
ARG VERSION=2020-07-16

ENV USERPWD mysec55rdet9966
USER root

ADD start.sh /
COPY alpine.patch /alpine.patch



RUN set -ex \
        && apk update \
        && apk add --no-cache nodejs npm \
        && apk add ca-certificates mailcap curl bash \
        && apk add --no-cache --virtual .build-deps make gcc g++ python3 git \
        && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
        && echo "Asia/Shanghai" > /etc/timezone

ARG VERSION
RUN set -ex \
        && git clone https://github.com/dissipator/gd-utils-noport.git /gd-utils \
        && cd /gd-utils \
        && npm install \
        && apk del .build-deps

VOLUME /gd-utils


ENTRYPOINT [ "node /gd-utils/index.js" ]
